apiVersion: apps/v1
kind: Deployment
metadata:
  name: impact-graph-deployment
spec:
  selector:
    matchLabels:
      app: impact-graph
  replicas: 1
  template:
    metadata:
      labels:
        app: impact-graph
    spec:
      containers:
        - name: impact-graph
          image: gaiagivescr.azurecr.io/impact-graph:3ee24eb30ca04c0f9ab069dffda06c6e76a0ebac
          imagePullPolicy: Always
          ports:
            - containerPort: 3000
              protocol: TCP
          envFrom:
            - configMapRef:
                name: impact-graph-config
          volumeMounts:
            - mountPath: /app/utils/public
              name: impact-graph-data
              subPath: applications
      volumes:
        - name: impact-graph-data
          persistentVolumeClaim:
            claimName: impact-graph-data-disk
