apiVersion: apps/v1
kind: Deployment
metadata:
  name: impact-graph-deployment
spec:
  selector:
    matchLabels:
      app: impact-graph
  replicas: 1
  template:
    metadata:
      labels:
        app: impact-graph
    spec:
      containers:
        - name: impact-graph
          image: gaiagivescr.azurecr.io/impact-graph:db84684cfe6c0d3c28d9c34468e0d2bc0b299d5d
          imagePullPolicy: Always
          ports:
            - containerPort: 3000
              protocol: TCP
          envFrom:
            - configMapRef:
                name: impact-graph-config
