apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgres-data-disk
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: managed-premium
  resources:
    requests:
      storage: 5Gi
