on:
  push:
    branches:
      - master
      - develop
name: kubernetes

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@main
      - uses: azure/docker-login@v1
        with:
          login-server: ${{ secrets.REGISTRY_LOGIN_SERVER }}
          username: ${{ secrets.REGISTRY_USERNAME }}
          password: ${{ secrets.REGISTRY_PASSWORD }}
      - run: |
          docker build . -t ${{ secrets.REGISTRY_LOGIN_SERVER }}/impact-graph:${{ github.sha }}
          docker push ${{ secrets.REGISTRY_LOGIN_SERVER }}/impact-graph:${{ github.sha }}
      - uses: azure/aks-set-context@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}
          resource-group: ${{ secrets.RESOURCE_GROUP }}
          cluster-name: ${{ secrets.CLUSTER_NAME }}
        id: login
      - uses: azure/k8s-deploy@v1.4
        with:
          manifests: |
            infrastructure/impact-graph-deployment.yml
            infrastructure/impact-graph-ingress.yml
            infrastructure/impact-graph-service.yml
          images: ${{ secrets.REGISTRY_LOGIN_SERVER }}/impact-graph:${{ github.sha }}
          kubectl-version: "latest"
